# Generated by Django 4.1.2 on 2023-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_todo_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
