# Generated by Django 4.1.2 on 2023-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='completed',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
